### ISSUE TITLE
Problem with establish_new_bt

### ISSUE THREAD

**Issue by Polina12910** [blaserlab/datascience.curriculum#10]
Hi Brad,

when I tried to run the line 
establish_new_bt(cache_path = "<some_directory>/r_4_2_cache", project_path = "<some_directory>/projects")

I got the following error: 
Error in establish_new_bt(cache_path = "<some_directory>/r_4_2_cache",  : 
  could not find function "establish_new_bt"

How should I proceed? I have not tried any of the subsequent code yet.

thanks!

Polina

**Comment by Polina12910** [comment]
The issue appears to have resolved itself. Not sure why it was a problem initially. I have an additional question: which file are we supposed to delete here: 

# initialize github
usethis::use_github(private = TRUE)
### Delete this file after initializing the project! ###

I currently have the following git status:
# A tibble: 3 × 3
  file                     status   staged
  <chr>                    <chr>    <lgl> 
1 R/example_immune_recon.R modified FALSE 
2 R/polina_scratch.R       modified FALSE 
3 R/ScratchLectures.R      modified FALSE 

is this OK or should something be deleted?

thanks!

**Comment by blaserlab** [comment]
This looks fine.

We didn't get all the way through using the git commands in class.  I realized that after.  Will cover it first thing next time.  But it is really easy.  You just run those lines at the top of git_commands.R:

`gert::git_status()`
`blaseRtemplates::write_project_library_catalog()`
`gert::git_add("*")`
`gert::git_commit("<commit message>")`
`blaseRtemplates::git_push_all()`

What you have there is telling you that you have modified those three files, but haven't staged them.  Staged is a synonym for "Add".  Adding/staging files means that git has calculated all of the changes you have made to them and is ready to commit those changes.  Commit is like a save point for your project.  When staged == FALSE, it just means that git recognizes a change has been made. 

The initialize file can be deleted at any point after you have run through all of the lines.  I usually delete it right away.  Does this answer your questions?

**Comment by Polina12910** [comment]
Hi Brad,

is the initializer file the one that I am typing the commands in? Is it necessary to delete it? This is one of my scratch files that I have been using to practice in.

Also, I created a new file to use as Lecture 2 scratch file in the Baseprojects folder. I am getting the following error when running the lines to commit:
[ main ] > blaseRtemplates::git_push_all()
Looking up https credentials for https://github.com/blaserlab/polina.git
Error in libgit2::git_remote_push : 
  cannot push because a reference that you are trying to update on the remote contains commits that are not present locally.

How can I fix this? thanks!

Polina

**Comment by blaserlab** [comment]
Couple of things:

The file you want to delete is named initialization.R.  It is created automatically when you initialize the project.  Once you run through the commands, you don't need it any more so it can be deleted.

git_commands.R contains the commands you will be using on a daily basis with git.  You want to keep that file around.  I will go through this at the beginning of the next class.

You don't want to do any work in the baseproject.  That is mostly there as a backstop so you always are working in a project.  This is important for good organization of your work, but also prevents you from overwriting things in random directories you may have ended up in unintentionally.  

So from the baseproject you want to initialize a new project for the class for example.  

Since you and I have a collaborative project, we have to use a slightly more complicated workflow where we work in branches to prevent conflicts like you are seeing.  I would recommend that you make a new project for your work in the class.  If you come by the office at some point I can fix what is going on with your polina project.
