### ISSUE TITLE
Default branch error

### ISSUE THREAD

**Issue by hklimaszewski** [blaserlab/datascience.curriculum#12]
I got behind on classes, just finishing up lesson one. I was getting an error and tried to figure it out on my own but I am very lost now..

I thought I had gotten through through adding the git pane and posting the repository to github but some things didn't look right. My console was saying [master] before each line of code. Also, my repository was appearing on github but it was called baseproject, unlike yours that said rclass_project_2023. After this I realized I was working in the wrong project. I deleted the base project repository from the github. I went into the rclass_project_2023 on Rstudio and repeated the initiaization steps. Now I am getting this errror when i try to run the initialize github command. 

> usethis::use_github(private = FALSE)
 Error in `git_default_branch()`: ! Can't determine the local repo's default branch. Run `rlang::last_trace()` to see where the error occurred.
>rlang::last_trace()
<error/error_default_branch>
Error in `git_default_branch()`:
! Can't determine the local repo's
  default branch.
---
Backtrace:
    ▆
 1. └─usethis::use_github(private = FALSE)
 2.   └─usethis::git_default_branch()

**Comment by hklimaszewski** [comment]
I messed around some more and got the repository to post! But I did get this message

Warning message:
In gitcreds_get_cache(cache_ev) :
  Invalid gitcreds credentials in env var `GITHUB_PAT_GITHUB_COM`. Maybe an unescaped ':' character?

**Comment by blaserlab** [comment]
OK great.  Looks like you figured it out.  The hardest part is getting things (blaseRtemplates, git, github) set up initially.  But you also have to get used to always working in a project, which may not be how you have worked before.  

The [ master ] thing is an indicator to tell you what git branch you are on.  It may also say "main" which is the same thing.  This is a helper for people who are collaborating on projects.  It uses git branches to help incorporate changes from different contributors.  There is a section on git_commands.R that tells you how this works.  That part of the script will work equally well on your own or when collaborating on a project, so you can use it if you want.  I don't go over collaborating on projects in the class because there are a few other things involved that can be more confusing, related to stuff you need to do with github.  Also most people work on their own.  If you want to know how this works, I can show you...let me know.

Honestly I don't know why that warning occurs.  It doesn't seem to indicate a real problem so I haven't done much work to sort it out.  I get that warning too on all of my systems.  It happens once per session, I believe and then goes away.
