### ISSUE TITLE
Can someone explain what RENV does exactly? 

### ISSUE THREAD

**Issue by narsilvw** [blaserlab/datascience.curriculum#6]

**Comment by blaserlab** [comment]
It has 2 main purposes:

1. Maintains a list of the packages (with source, version number and unique identifier, etc) that you are using.  This is called a lockfile.  It lets future-you or anyone working with you install and use the same set of packages that you are using in the project.  This is a good thing because sometimes packages change and this could change your results.

2.  Maintains a "cache" of packages in a hard-to-find place on your computer and then links them into your  project.  This is good because it gives you quick access to multiple versions of packages in any number of projects without taking up any disk space on your computer.
